# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e9bbf3d34446aa0e5a94795fbe01148"
application_url = "https://bulk-invites.test/"
embedded = true
name = "Local: Smart Invite & Login"
handle = "local-smart-invite-and-login"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhook/shop-redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://bulk-invites.test/authenticate" ]

[pos]
embedded = false
